# Generated by Django 4.0.3 on 2022-04-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_id', models.IntegerField()),
                ('Sug_1', models.CharField(max_length=300)),
                ('Sug_2', models.CharField(max_length=300)),
                ('Sug_3', models.CharField(max_length=300)),
                ('Sug_4', models.CharField(max_length=300)),
                ('Sug_5', models.CharField(max_length=300)),
                ('Sug_6', models.CharField(max_length=300)),
                ('Sug_7', models.CharField(max_length=300)),
                ('Sug_8', models.CharField(max_length=300)),
                ('Sug_9', models.CharField(max_length=300)),
                ('Sug_10', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Movie_List',
            },
        ),
    ]
