# Generated by Django 4.0.3 on 2022-04-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_list',
            name='Sug_1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='Sug_10',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='Sug_2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='Sug_3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='Sug_4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='Sug_5',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='Sug_6',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='Sug_7',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='Sug_8',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='Sug_9',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterModelTable(
            name='movie_list',
            table='Movie_list',
        ),
    ]
