# Generated by Django 4.0.3 on 2022-04-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0002_alter_movie_list_sug_1_alter_movie_list_sug_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_list',
            name='Movie_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterModelTable(
            name='movie_list',
            table=None,
        ),
    ]
