# Generated by Django 4.0.3 on 2022-04-25 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0003_movie_list_movie_name_alter_movie_list_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie_list',
            table='Movie_list',
        ),
    ]
