# Generated by Django 4.0.3 on 2022-05-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs', '0004_alter_movie_list_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
